[package]
name = "embedding_proof"
type = "bin"
authors = [""]
# Best practice: Specify the compiler version you are using
compiler_version = ">=0.27.0"

[dependencies]
poseidon = { tag = "v0.1.1", git = "https://github.com/noir-lang/poseidon" }