/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { StateVars } from './StateVars.js';
export type { ZKBioRegistry } from './ZKBioRegistry.js';
export * as factories from './factories/index.js';
export { StateVars__factory } from './factories/StateVars__factory.js';
export { ZKBioRegistry__factory } from './factories/ZKBioRegistry__factory.js';