/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface StateVarsInterface extends Interface {
    getFunction(nameOrSignature: "commiter"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Commitment"): EventFragment;

    encodeFunctionData(functionFragment: 'commiter', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'commiter', data: BytesLike): Result;
  }

  
    export namespace CommitmentEvent {
      export type InputTuple = [id: string, p_hash: BigNumberish];
      export type OutputTuple = [id: string, p_hash: bigint];
      export interface OutputObject {id: string, p_hash: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface StateVars extends BaseContract {
    
    connect(runner?: ContractRunner | null): StateVars;
    waitForDeployment(): Promise<this>;

    interface: StateVarsInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    commiter: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'commiter'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'Commitment'): TypedContractEvent<CommitmentEvent.InputTuple, CommitmentEvent.OutputTuple, CommitmentEvent.OutputObject>;

    filters: {
      
      'Commitment(string,uint256)': TypedContractEvent<CommitmentEvent.InputTuple, CommitmentEvent.OutputTuple, CommitmentEvent.OutputObject>;
      Commitment: TypedContractEvent<CommitmentEvent.InputTuple, CommitmentEvent.OutputTuple, CommitmentEvent.OutputObject>;
    
    };
  }