/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface ZKBioRegistryInterface extends Interface {
    getFunction(nameOrSignature: "commit" | "commiter" | "reterieve" | "updateCommitter"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Commitment"): EventFragment;

    encodeFunctionData(functionFragment: 'commit', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'commiter', values?: undefined): string;
encodeFunctionData(functionFragment: 'reterieve', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'updateCommitter', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'commit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'commiter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reterieve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateCommitter', data: BytesLike): Result;
  }

  
    export namespace CommitmentEvent {
      export type InputTuple = [id: BigNumberish, p_hash: BigNumberish];
      export type OutputTuple = [id: bigint, p_hash: bigint];
      export interface OutputObject {id: bigint, p_hash: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ZKBioRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): ZKBioRegistry;
    waitForDeployment(): Promise<this>;

    interface: ZKBioRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    commit: TypedContractMethod<
      [id: BigNumberish, p_hash: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    commiter: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    reterieve: TypedContractMethod<
      [id: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    updateCommitter: TypedContractMethod<
      [newCommitter: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'commit'): TypedContractMethod<
      [id: BigNumberish, p_hash: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'commiter'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'reterieve'): TypedContractMethod<
      [id: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'updateCommitter'): TypedContractMethod<
      [newCommitter: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'Commitment'): TypedContractEvent<CommitmentEvent.InputTuple, CommitmentEvent.OutputTuple, CommitmentEvent.OutputObject>;

    filters: {
      
      'Commitment(uint256,uint256)': TypedContractEvent<CommitmentEvent.InputTuple, CommitmentEvent.OutputTuple, CommitmentEvent.OutputObject>;
      Commitment: TypedContractEvent<CommitmentEvent.InputTuple, CommitmentEvent.OutputTuple, CommitmentEvent.OutputObject>;
    
    };
  }