/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { StateVars__factory } from './StateVars__factory.js';
export { ZKBioRegistry__factory } from './ZKBioRegistry__factory.js';