/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { StateVars, StateVarsInterface } from "../StateVars.js";

  const _abi = [
  {
    "inputs": [],
    "name": "InvalidCommiter",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "string",
        "name": "id",
        "type": "string"
      },
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "p_hash",
        "type": "uint256"
      }
    ],
    "name": "Commitment",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "commiter",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class StateVars__factory {
    static readonly abi = _abi;
    static createInterface(): StateVarsInterface {
      return new Interface(_abi) as StateVarsInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): StateVars {
      return new Contract(address, _abi, runner) as unknown as StateVars;
    }
  }
  